### PR TITLE
Eslam's commit

### PR DESCRIPTION
**Pull request by EEslamo**
Problem with saving a huge file: saving error

### CODE REVIEW

**Review by NourrAdel — COMMENTED** [review]
Checked

**Review by EyadHanyMatador — COMMENTED** [review]
checked!

**Review by youssefhatem03 — APPROVED** [review]

**Review by Mahdy101 — APPROVED** [review]
checked

**Review by NourrAdel — COMMENTED** [review]
Great Work Eslamo !

**Review by youssefhatem03 — APPROVED** [review]

**Pull request closed without merging**
